name: expense_planner
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1


  cupertino_icons: ^1.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/fonts/images/


fonts:
  - family: OpenSans
    fonts:
      - assets: assets/fonts/OpenSans-Regular.ttf
      - assets: assets/fonts/OpenSans-Bold.ttf
        weight: 700
  - family: QuickSand
    fonts:
      - assets: assets/fonts/QuickSand-Regular.ttf
      - assets: assets/fonts/QuickSand-Bold.ttf    
        weight: 700


